development:
  clients:
    default:
      database: lab2_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: lab2_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0
